Trait {
	#name : #TMGTimeTravelEvents,
	#traits : 'MolComponentEvents',
	#classTraits : 'MolComponentEvents classTrait',
	#category : #MolGPSTimeTravel
}

{ #category : #events }
TMGTimeTravelEvents >> restoreFrom: aMemento [

	
]

{ #category : #events }
TMGTimeTravelEvents >> saveForTimeTravel [

	
]

{ #category : #events }
TMGTimeTravelEvents >> startTimeTravel [

	
]

{ #category : #events }
TMGTimeTravelEvents >> stopTimeTravel [

	
]
