Trait {
	#name : #TMGTimeTravelServices,
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : #MolGPSTimeTravel
}

{ #category : #services }
TMGTimeTravelServices >> creationOf: aComponentMemento at: aStep [

]

{ #category : #services }
TMGTimeTravelServices >> initializationAt: aStep [

	
]

{ #category : #services }
TMGTimeTravelServices >> isRestoring [

	
]

{ #category : #services }
TMGTimeTravelServices >> removeOf: aComponentMemento at: aStep [
]

{ #category : #services }
TMGTimeTravelServices >> save: aComponent at: aStep [
]

{ #category : #services }
TMGTimeTravelServices >> saveTheSimulationAt: aStep [

	
]
