Trait {
	#name : #TMGTimeTravelServices,
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : #MolGPSTimeTravel
}

{ #category : #services }
TMGTimeTravelServices >> creationOf: aComponent [

	
]

{ #category : #services }
TMGTimeTravelServices >> deletionOf: aComponent [

	
]

{ #category : #services }
TMGTimeTravelServices >> initializationAt: aStep [

	
]

{ #category : #services }
TMGTimeTravelServices >> isRestoring [

	
]

{ #category : #services }
TMGTimeTravelServices >> save: aComponent [

	
]

{ #category : #services }
TMGTimeTravelServices >> saveTheSystem [

	
]
